[package]
name = "squish"
version = "0.1.0"
edition = "2024"

[dependencies]
rustyline = "13"
colored = "2"
chrono = { version = "0.4", default-features = false, features = ["std","clock"] }
humansize = "2"
which = "6"
glob = "0.3"
libc = "0.2"
